parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{SignUp/Entity,Infrastructure/Migrations,Infrastructure/Framework/Symfony/Kernel.php}'
